### ISSUE TITLE
Notes from meeting - Early Oct 2016

### ISSUE THREAD

**Issue by aligreene** [sheilak/watercooler#31]
Image in lists are portrait should be landscape

Logo to be developed - W could be antenna?? TV needs to feature? 

Group cards - icons and text hard to read

Make primary group should be ticked as default 

Watched / not watched is confusing on profile pics 

Episode view - 
Groups should be below the summary of show. Episode don't necessarily need a pic or summary. Just episode abs season number and if there's a title 

Add a group / people view - we are missing the context of what show you're adding people to - need to include the show you're about to connect a group with.

**Comment by mollymules** [comment]
Created sub-issues
